#!/bin/bash
#install dependencies, repo, etc. Ansible
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible
sudo apt-get install -y python-pip
pip install docker-py
mkdir importfiles
GITHUB=https://raw.githubusercontent.com/stephanmarissen/Testing/master
wget $GITHUB/a.yml && wget $GITHUB/b.yml && wget $GITHUB/vars.yml && wget $GITHUB/docker-entrypoint.sh && wget $GITHUB/Dockerfile && wget -P /importfiles $GITHUB/writers.sql
sudo apt-get install -y git


#install dependencies, repo, etc. Docker
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce
sudo gpasswd -a $USER docker
newgrp docker
